/**
 *
 *  Project.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Project.h"
#include "User.h"
#include "UserProject.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::postgres;

const std::string Project::Cols::_id = "\"id\"";
const std::string Project::Cols::_name = "\"name\"";
const std::string Project::Cols::_source_path = "\"source_path\"";
const std::string Project::Cols::_source_repo = "\"source_repo\"";
const std::string Project::Cols::_source_branch = "\"source_branch\"";
const std::string Project::Cols::_is_community = "\"is_community\"";
const std::string Project::Cols::_type = "\"type\"";
const std::string Project::Cols::_platforms = "\"platforms\"";
const std::string Project::Cols::_search_vector = "\"search_vector\"";
const std::string Project::Cols::_created_at = "\"created_at\"";
const std::string Project::Cols::_is_public = "\"is_public\"";
const std::string Project::primaryKeyName = "id";
const bool Project::hasPrimaryKey = true;
const std::string Project::tableName = "\"project\"";

const std::vector<typename Project::MetaData> Project::metaData_={
{"id","std::string","text",0,0,1,1},
{"name","std::string","text",0,0,0,1},
{"source_path","std::string","text",0,0,0,1},
{"source_repo","std::string","text",0,0,0,1},
{"source_branch","std::string","text",0,0,0,1},
{"is_community","bool","boolean",1,0,0,1},
{"type","std::string","character varying",255,0,0,1},
{"platforms","std::string","character varying",255,0,0,1},
{"search_vector","std::string","tsvector",0,0,0,0},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,1},
{"is_public","bool","boolean",1,0,0,1}
};
const std::string &Project::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Project::Project(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["source_path"].isNull())
        {
            sourcePath_=std::make_shared<std::string>(r["source_path"].as<std::string>());
        }
        if(!r["source_repo"].isNull())
        {
            sourceRepo_=std::make_shared<std::string>(r["source_repo"].as<std::string>());
        }
        if(!r["source_branch"].isNull())
        {
            sourceBranch_=std::make_shared<std::string>(r["source_branch"].as<std::string>());
        }
        if(!r["is_community"].isNull())
        {
            isCommunity_=std::make_shared<bool>(r["is_community"].as<bool>());
        }
        if(!r["type"].isNull())
        {
            type_=std::make_shared<std::string>(r["type"].as<std::string>());
        }
        if(!r["platforms"].isNull())
        {
            platforms_=std::make_shared<std::string>(r["platforms"].as<std::string>());
        }
        if(!r["search_vector"].isNull())
        {
            searchVector_=std::make_shared<std::string>(r["search_vector"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["is_public"].isNull())
        {
            isPublic_=std::make_shared<bool>(r["is_public"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 11 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            sourcePath_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            sourceRepo_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            sourceBranch_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            isCommunity_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            type_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            platforms_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            searchVector_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            isPublic_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

Project::Project(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            sourcePath_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            sourceRepo_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            sourceBranch_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            isCommunity_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            type_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            platforms_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            searchVector_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            isPublic_=std::make_shared<bool>(pJson[pMasqueradingVector[10]].asBool());
        }
    }
}

Project::Project(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("source_path"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["source_path"].isNull())
        {
            sourcePath_=std::make_shared<std::string>(pJson["source_path"].asString());
        }
    }
    if(pJson.isMember("source_repo"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["source_repo"].isNull())
        {
            sourceRepo_=std::make_shared<std::string>(pJson["source_repo"].asString());
        }
    }
    if(pJson.isMember("source_branch"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["source_branch"].isNull())
        {
            sourceBranch_=std::make_shared<std::string>(pJson["source_branch"].asString());
        }
    }
    if(pJson.isMember("is_community"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["is_community"].isNull())
        {
            isCommunity_=std::make_shared<bool>(pJson["is_community"].asBool());
        }
    }
    if(pJson.isMember("type"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["type"].isNull())
        {
            type_=std::make_shared<std::string>(pJson["type"].asString());
        }
    }
    if(pJson.isMember("platforms"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["platforms"].isNull())
        {
            platforms_=std::make_shared<std::string>(pJson["platforms"].asString());
        }
    }
    if(pJson.isMember("search_vector"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["search_vector"].isNull())
        {
            searchVector_=std::make_shared<std::string>(pJson["search_vector"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_public"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["is_public"].isNull())
        {
            isPublic_=std::make_shared<bool>(pJson["is_public"].asBool());
        }
    }
}

void Project::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            sourcePath_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            sourceRepo_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            sourceBranch_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            isCommunity_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            type_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            platforms_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            searchVector_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            isPublic_=std::make_shared<bool>(pJson[pMasqueradingVector[10]].asBool());
        }
    }
}

void Project::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("source_path"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["source_path"].isNull())
        {
            sourcePath_=std::make_shared<std::string>(pJson["source_path"].asString());
        }
    }
    if(pJson.isMember("source_repo"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["source_repo"].isNull())
        {
            sourceRepo_=std::make_shared<std::string>(pJson["source_repo"].asString());
        }
    }
    if(pJson.isMember("source_branch"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["source_branch"].isNull())
        {
            sourceBranch_=std::make_shared<std::string>(pJson["source_branch"].asString());
        }
    }
    if(pJson.isMember("is_community"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["is_community"].isNull())
        {
            isCommunity_=std::make_shared<bool>(pJson["is_community"].asBool());
        }
    }
    if(pJson.isMember("type"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["type"].isNull())
        {
            type_=std::make_shared<std::string>(pJson["type"].asString());
        }
    }
    if(pJson.isMember("platforms"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["platforms"].isNull())
        {
            platforms_=std::make_shared<std::string>(pJson["platforms"].asString());
        }
    }
    if(pJson.isMember("search_vector"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["search_vector"].isNull())
        {
            searchVector_=std::make_shared<std::string>(pJson["search_vector"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_public"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["is_public"].isNull())
        {
            isPublic_=std::make_shared<bool>(pJson["is_public"].asBool());
        }
    }
}

const std::string &Project::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Project::getId() const noexcept
{
    return id_;
}
void Project::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void Project::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename Project::PrimaryKeyType & Project::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Project::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Project::getName() const noexcept
{
    return name_;
}
void Project::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void Project::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}

const std::string &Project::getValueOfSourcePath() const noexcept
{
    static const std::string defaultValue = std::string();
    if(sourcePath_)
        return *sourcePath_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Project::getSourcePath() const noexcept
{
    return sourcePath_;
}
void Project::setSourcePath(const std::string &pSourcePath) noexcept
{
    sourcePath_ = std::make_shared<std::string>(pSourcePath);
    dirtyFlag_[2] = true;
}
void Project::setSourcePath(std::string &&pSourcePath) noexcept
{
    sourcePath_ = std::make_shared<std::string>(std::move(pSourcePath));
    dirtyFlag_[2] = true;
}

const std::string &Project::getValueOfSourceRepo() const noexcept
{
    static const std::string defaultValue = std::string();
    if(sourceRepo_)
        return *sourceRepo_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Project::getSourceRepo() const noexcept
{
    return sourceRepo_;
}
void Project::setSourceRepo(const std::string &pSourceRepo) noexcept
{
    sourceRepo_ = std::make_shared<std::string>(pSourceRepo);
    dirtyFlag_[3] = true;
}
void Project::setSourceRepo(std::string &&pSourceRepo) noexcept
{
    sourceRepo_ = std::make_shared<std::string>(std::move(pSourceRepo));
    dirtyFlag_[3] = true;
}

const std::string &Project::getValueOfSourceBranch() const noexcept
{
    static const std::string defaultValue = std::string();
    if(sourceBranch_)
        return *sourceBranch_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Project::getSourceBranch() const noexcept
{
    return sourceBranch_;
}
void Project::setSourceBranch(const std::string &pSourceBranch) noexcept
{
    sourceBranch_ = std::make_shared<std::string>(pSourceBranch);
    dirtyFlag_[4] = true;
}
void Project::setSourceBranch(std::string &&pSourceBranch) noexcept
{
    sourceBranch_ = std::make_shared<std::string>(std::move(pSourceBranch));
    dirtyFlag_[4] = true;
}

const bool &Project::getValueOfIsCommunity() const noexcept
{
    static const bool defaultValue = bool();
    if(isCommunity_)
        return *isCommunity_;
    return defaultValue;
}
const std::shared_ptr<bool> &Project::getIsCommunity() const noexcept
{
    return isCommunity_;
}
void Project::setIsCommunity(const bool &pIsCommunity) noexcept
{
    isCommunity_ = std::make_shared<bool>(pIsCommunity);
    dirtyFlag_[5] = true;
}

const std::string &Project::getValueOfType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(type_)
        return *type_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Project::getType() const noexcept
{
    return type_;
}
void Project::setType(const std::string &pType) noexcept
{
    type_ = std::make_shared<std::string>(pType);
    dirtyFlag_[6] = true;
}
void Project::setType(std::string &&pType) noexcept
{
    type_ = std::make_shared<std::string>(std::move(pType));
    dirtyFlag_[6] = true;
}

const std::string &Project::getValueOfPlatforms() const noexcept
{
    static const std::string defaultValue = std::string();
    if(platforms_)
        return *platforms_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Project::getPlatforms() const noexcept
{
    return platforms_;
}
void Project::setPlatforms(const std::string &pPlatforms) noexcept
{
    platforms_ = std::make_shared<std::string>(pPlatforms);
    dirtyFlag_[7] = true;
}
void Project::setPlatforms(std::string &&pPlatforms) noexcept
{
    platforms_ = std::make_shared<std::string>(std::move(pPlatforms));
    dirtyFlag_[7] = true;
}

const std::string &Project::getValueOfSearchVector() const noexcept
{
    static const std::string defaultValue = std::string();
    if(searchVector_)
        return *searchVector_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Project::getSearchVector() const noexcept
{
    return searchVector_;
}
void Project::setSearchVector(const std::string &pSearchVector) noexcept
{
    searchVector_ = std::make_shared<std::string>(pSearchVector);
    dirtyFlag_[8] = true;
}
void Project::setSearchVector(std::string &&pSearchVector) noexcept
{
    searchVector_ = std::make_shared<std::string>(std::move(pSearchVector));
    dirtyFlag_[8] = true;
}
void Project::setSearchVectorToNull() noexcept
{
    searchVector_.reset();
    dirtyFlag_[8] = true;
}

const ::trantor::Date &Project::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Project::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Project::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[9] = true;
}

const bool &Project::getValueOfIsPublic() const noexcept
{
    static const bool defaultValue = bool();
    if(isPublic_)
        return *isPublic_;
    return defaultValue;
}
const std::shared_ptr<bool> &Project::getIsPublic() const noexcept
{
    return isPublic_;
}
void Project::setIsPublic(const bool &pIsPublic) noexcept
{
    isPublic_ = std::make_shared<bool>(pIsPublic);
    dirtyFlag_[10] = true;
}

void Project::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Project::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "name",
        "source_path",
        "source_repo",
        "source_branch",
        "is_community",
        "type",
        "platforms",
        "search_vector",
        "created_at",
        "is_public"
    };
    return inCols;
}

void Project::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSourcePath())
        {
            binder << getValueOfSourcePath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSourceRepo())
        {
            binder << getValueOfSourceRepo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSourceBranch())
        {
            binder << getValueOfSourceBranch();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getIsCommunity())
        {
            binder << getValueOfIsCommunity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getType())
        {
            binder << getValueOfType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getPlatforms())
        {
            binder << getValueOfPlatforms();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getSearchVector())
        {
            binder << getValueOfSearchVector();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getIsPublic())
        {
            binder << getValueOfIsPublic();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Project::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    return ret;
}

void Project::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSourcePath())
        {
            binder << getValueOfSourcePath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSourceRepo())
        {
            binder << getValueOfSourceRepo();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSourceBranch())
        {
            binder << getValueOfSourceBranch();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getIsCommunity())
        {
            binder << getValueOfIsCommunity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getType())
        {
            binder << getValueOfType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getPlatforms())
        {
            binder << getValueOfPlatforms();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getSearchVector())
        {
            binder << getValueOfSearchVector();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getIsPublic())
        {
            binder << getValueOfIsPublic();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Project::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getSourcePath())
    {
        ret["source_path"]=getValueOfSourcePath();
    }
    else
    {
        ret["source_path"]=Json::Value();
    }
    if(getSourceRepo())
    {
        ret["source_repo"]=getValueOfSourceRepo();
    }
    else
    {
        ret["source_repo"]=Json::Value();
    }
    if(getSourceBranch())
    {
        ret["source_branch"]=getValueOfSourceBranch();
    }
    else
    {
        ret["source_branch"]=Json::Value();
    }
    if(getIsCommunity())
    {
        ret["is_community"]=getValueOfIsCommunity();
    }
    else
    {
        ret["is_community"]=Json::Value();
    }
    if(getType())
    {
        ret["type"]=getValueOfType();
    }
    else
    {
        ret["type"]=Json::Value();
    }
    if(getPlatforms())
    {
        ret["platforms"]=getValueOfPlatforms();
    }
    else
    {
        ret["platforms"]=Json::Value();
    }
    if(getSearchVector())
    {
        ret["search_vector"]=getValueOfSearchVector();
    }
    else
    {
        ret["search_vector"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getIsPublic())
    {
        ret["is_public"]=getValueOfIsPublic();
    }
    else
    {
        ret["is_public"]=Json::Value();
    }
    return ret;
}

Json::Value Project::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 11)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[1]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getSourcePath())
            {
                ret[pMasqueradingVector[2]]=getValueOfSourcePath();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSourceRepo())
            {
                ret[pMasqueradingVector[3]]=getValueOfSourceRepo();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getSourceBranch())
            {
                ret[pMasqueradingVector[4]]=getValueOfSourceBranch();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getIsCommunity())
            {
                ret[pMasqueradingVector[5]]=getValueOfIsCommunity();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getType())
            {
                ret[pMasqueradingVector[6]]=getValueOfType();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getPlatforms())
            {
                ret[pMasqueradingVector[7]]=getValueOfPlatforms();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getSearchVector())
            {
                ret[pMasqueradingVector[8]]=getValueOfSearchVector();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[9]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getIsPublic())
            {
                ret[pMasqueradingVector[10]]=getValueOfIsPublic();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getSourcePath())
    {
        ret["source_path"]=getValueOfSourcePath();
    }
    else
    {
        ret["source_path"]=Json::Value();
    }
    if(getSourceRepo())
    {
        ret["source_repo"]=getValueOfSourceRepo();
    }
    else
    {
        ret["source_repo"]=Json::Value();
    }
    if(getSourceBranch())
    {
        ret["source_branch"]=getValueOfSourceBranch();
    }
    else
    {
        ret["source_branch"]=Json::Value();
    }
    if(getIsCommunity())
    {
        ret["is_community"]=getValueOfIsCommunity();
    }
    else
    {
        ret["is_community"]=Json::Value();
    }
    if(getType())
    {
        ret["type"]=getValueOfType();
    }
    else
    {
        ret["type"]=Json::Value();
    }
    if(getPlatforms())
    {
        ret["platforms"]=getValueOfPlatforms();
    }
    else
    {
        ret["platforms"]=Json::Value();
    }
    if(getSearchVector())
    {
        ret["search_vector"]=getValueOfSearchVector();
    }
    else
    {
        ret["search_vector"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getIsPublic())
    {
        ret["is_public"]=getValueOfIsPublic();
    }
    else
    {
        ret["is_public"]=Json::Value();
    }
    return ret;
}

bool Project::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("source_path"))
    {
        if(!validJsonOfField(2, "source_path", pJson["source_path"], err, true))
            return false;
    }
    else
    {
        err="The source_path column cannot be null";
        return false;
    }
    if(pJson.isMember("source_repo"))
    {
        if(!validJsonOfField(3, "source_repo", pJson["source_repo"], err, true))
            return false;
    }
    else
    {
        err="The source_repo column cannot be null";
        return false;
    }
    if(pJson.isMember("source_branch"))
    {
        if(!validJsonOfField(4, "source_branch", pJson["source_branch"], err, true))
            return false;
    }
    else
    {
        err="The source_branch column cannot be null";
        return false;
    }
    if(pJson.isMember("is_community"))
    {
        if(!validJsonOfField(5, "is_community", pJson["is_community"], err, true))
            return false;
    }
    if(pJson.isMember("type"))
    {
        if(!validJsonOfField(6, "type", pJson["type"], err, true))
            return false;
    }
    else
    {
        err="The type column cannot be null";
        return false;
    }
    if(pJson.isMember("platforms"))
    {
        if(!validJsonOfField(7, "platforms", pJson["platforms"], err, true))
            return false;
    }
    else
    {
        err="The platforms column cannot be null";
        return false;
    }
    if(pJson.isMember("search_vector"))
    {
        if(!validJsonOfField(8, "search_vector", pJson["search_vector"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(9, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("is_public"))
    {
        if(!validJsonOfField(10, "is_public", pJson["is_public"], err, true))
            return false;
    }
    return true;
}
bool Project::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Project::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("source_path"))
    {
        if(!validJsonOfField(2, "source_path", pJson["source_path"], err, false))
            return false;
    }
    if(pJson.isMember("source_repo"))
    {
        if(!validJsonOfField(3, "source_repo", pJson["source_repo"], err, false))
            return false;
    }
    if(pJson.isMember("source_branch"))
    {
        if(!validJsonOfField(4, "source_branch", pJson["source_branch"], err, false))
            return false;
    }
    if(pJson.isMember("is_community"))
    {
        if(!validJsonOfField(5, "is_community", pJson["is_community"], err, false))
            return false;
    }
    if(pJson.isMember("type"))
    {
        if(!validJsonOfField(6, "type", pJson["type"], err, false))
            return false;
    }
    if(pJson.isMember("platforms"))
    {
        if(!validJsonOfField(7, "platforms", pJson["platforms"], err, false))
            return false;
    }
    if(pJson.isMember("search_vector"))
    {
        if(!validJsonOfField(8, "search_vector", pJson["search_vector"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(9, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("is_public"))
    {
        if(!validJsonOfField(10, "is_public", pJson["is_public"], err, false))
            return false;
    }
    return true;
}
bool Project::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Project::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
std::vector<std::pair<User,UserProject>> Project::getUsers(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from user_,user_project where user_project.project_id = $1 and user_project.user_id = user_.id";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<std::pair<User,UserProject>> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(std::pair<User,UserProject>(
            User(row),UserProject(row,User::getColumnNumber())));
    }
    return ret;
}

void Project::getUsers(const DbClientPtr &clientPtr,
                       const std::function<void(std::vector<std::pair<User,UserProject>>)> &rcb,
                       const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from user_,user_project where user_project.project_id = $1 and user_project.user_id = user_.id";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<std::pair<User,UserProject>> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(std::pair<User,UserProject>(
                           User(row),UserProject(row,User::getColumnNumber())));
                   }
                   rcb(ret);
               }
               >> ecb;
}
