/**
 *
 *  RecipeType.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "RecipeType.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::postgres;

const std::string RecipeType::Cols::_id = "\"id\"";
const std::string RecipeType::Cols::_loc = "\"loc\"";
const std::string RecipeType::Cols::_version_id = "\"version_id\"";
const std::string RecipeType::primaryKeyName = "id";
const bool RecipeType::hasPrimaryKey = true;
const std::string RecipeType::tableName = "\"recipe_type\"";

const std::vector<typename RecipeType::MetaData> RecipeType::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"loc","std::string","character varying",255,0,0,0},
{"version_id","int64_t","bigint",8,0,0,0}
};
const std::string &RecipeType::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
RecipeType::RecipeType(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["loc"].isNull())
        {
            loc_=std::make_shared<std::string>(r["loc"].as<std::string>());
        }
        if(!r["version_id"].isNull())
        {
            versionId_=std::make_shared<int64_t>(r["version_id"].as<int64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            loc_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            versionId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
    }

}

RecipeType::RecipeType(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            loc_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            versionId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

RecipeType::RecipeType(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("loc"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["loc"].isNull())
        {
            loc_=std::make_shared<std::string>(pJson["loc"].asString());
        }
    }
    if(pJson.isMember("version_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["version_id"].isNull())
        {
            versionId_=std::make_shared<int64_t>((int64_t)pJson["version_id"].asInt64());
        }
    }
}

void RecipeType::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            loc_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            versionId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
}

void RecipeType::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("loc"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["loc"].isNull())
        {
            loc_=std::make_shared<std::string>(pJson["loc"].asString());
        }
    }
    if(pJson.isMember("version_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["version_id"].isNull())
        {
            versionId_=std::make_shared<int64_t>((int64_t)pJson["version_id"].asInt64());
        }
    }
}

const int64_t &RecipeType::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &RecipeType::getId() const noexcept
{
    return id_;
}
void RecipeType::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename RecipeType::PrimaryKeyType & RecipeType::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &RecipeType::getValueOfLoc() const noexcept
{
    static const std::string defaultValue = std::string();
    if(loc_)
        return *loc_;
    return defaultValue;
}
const std::shared_ptr<std::string> &RecipeType::getLoc() const noexcept
{
    return loc_;
}
void RecipeType::setLoc(const std::string &pLoc) noexcept
{
    loc_ = std::make_shared<std::string>(pLoc);
    dirtyFlag_[1] = true;
}
void RecipeType::setLoc(std::string &&pLoc) noexcept
{
    loc_ = std::make_shared<std::string>(std::move(pLoc));
    dirtyFlag_[1] = true;
}
void RecipeType::setLocToNull() noexcept
{
    loc_.reset();
    dirtyFlag_[1] = true;
}

const int64_t &RecipeType::getValueOfVersionId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(versionId_)
        return *versionId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &RecipeType::getVersionId() const noexcept
{
    return versionId_;
}
void RecipeType::setVersionId(const int64_t &pVersionId) noexcept
{
    versionId_ = std::make_shared<int64_t>(pVersionId);
    dirtyFlag_[2] = true;
}
void RecipeType::setVersionIdToNull() noexcept
{
    versionId_.reset();
    dirtyFlag_[2] = true;
}

void RecipeType::updateId(const uint64_t id)
{
}

const std::vector<std::string> &RecipeType::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "loc",
        "version_id"
    };
    return inCols;
}

void RecipeType::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getLoc())
        {
            binder << getValueOfLoc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getVersionId())
        {
            binder << getValueOfVersionId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> RecipeType::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void RecipeType::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getLoc())
        {
            binder << getValueOfLoc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getVersionId())
        {
            binder << getValueOfVersionId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value RecipeType::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getLoc())
    {
        ret["loc"]=getValueOfLoc();
    }
    else
    {
        ret["loc"]=Json::Value();
    }
    if(getVersionId())
    {
        ret["version_id"]=(Json::Int64)getValueOfVersionId();
    }
    else
    {
        ret["version_id"]=Json::Value();
    }
    return ret;
}

Json::Value RecipeType::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getLoc())
            {
                ret[pMasqueradingVector[1]]=getValueOfLoc();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getVersionId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfVersionId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getLoc())
    {
        ret["loc"]=getValueOfLoc();
    }
    else
    {
        ret["loc"]=Json::Value();
    }
    if(getVersionId())
    {
        ret["version_id"]=(Json::Int64)getValueOfVersionId();
    }
    else
    {
        ret["version_id"]=Json::Value();
    }
    return ret;
}

bool RecipeType::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("loc"))
    {
        if(!validJsonOfField(1, "loc", pJson["loc"], err, true))
            return false;
    }
    if(pJson.isMember("version_id"))
    {
        if(!validJsonOfField(2, "version_id", pJson["version_id"], err, true))
            return false;
    }
    return true;
}
bool RecipeType::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool RecipeType::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("loc"))
    {
        if(!validJsonOfField(1, "loc", pJson["loc"], err, false))
            return false;
    }
    if(pJson.isMember("version_id"))
    {
        if(!validJsonOfField(2, "version_id", pJson["version_id"], err, false))
            return false;
    }
    return true;
}
bool RecipeType::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool RecipeType::validJsonOfField(size_t index,
                                  const std::string &fieldName,
                                  const Json::Value &pJson,
                                  std::string &err,
                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
