#pragma once

#ifdef DETECTED_PROJECT_VERSION

#define PROJECT_VERSION DETECTED_PROJECT_VERSION
#define PROJECT_GIT_HASH DETECTED_GIT_HASH
#define PROJECT_GIT_HASH_FULL DETECTED_GIT_HASH_FULL

#else

#define PROJECT_VERSION "unknown"
#define PROJECT_GIT_HASH "unknown"

#endif
